### ISSUE TITLE
Cannot mix incompatible Qt library (6.7.2) with this library (6.7.3)

### ISSUE THREAD

**Issue by tabetai** [flathub/org.kde.arianna#58] opened 2024-10-01 06:16 UTC
When I try to launch application I get this error:

`Cannot mix incompatible Qt library (6.7.2) with this library (6.7.3)`

Flatpak Version: 1.14.10
Operating System: Kubuntu 24.10
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.6.2
Kernel Version: 6.11.0-8-generic (64-bit)
Graphics Platform: Wayland

**Comment by Justinzobel** [comment] 2024-10-01 08:15
Interesting as nothing should have been updated to 6.7.3 yet.

**Comment by Justinzobel** [comment] 2024-10-01 08:21
Can confirm here, but all the Qt libs in the flatpak are 6.7.2.

```
libQt6PdfQuick.so -> x86_64-linux-gnu/libQt6PdfQuick.so.6.7.2
libQt6PdfQuick.so.6 -> x86_64-linux-gnu/libQt6PdfQuick.so.6.7.2
libQt6PdfQuick.so.6.7.2 -> x86_64-linux-gnu/libQt6PdfQuick.so.6.7.2
libQt6Pdf.so -> x86_64-linux-gnu/libQt6Pdf.so.6.7.2
libQt6Pdf.so.6 -> x86_64-linux-gnu/libQt6Pdf.so.6.7.2
libQt6Pdf.so.6.7.2 -> x86_64-linux-gnu/libQt6Pdf.so.6.7.2
libQt6PdfWidgets.so -> x86_64-linux-gnu/libQt6PdfWidgets.so.6.7.2
libQt6PdfWidgets.so.6 -> x86_64-linux-gnu/libQt6PdfWidgets.so.6.7.2
libQt6PdfWidgets.so.6.7.2 -> x86_64-linux-gnu/libQt6PdfWidgets.so.6.7.2
libQt6WebEngineCore.so -> x86_64-linux-gnu/libQt6WebEngineCore.so.6.7.2
libQt6WebEngineCore.so.6 -> x86_64-linux-gnu/libQt6WebEngineCore.so.6.7.2
libQt6WebEngineCore.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineCore.so.6.7.2
libQt6WebEngineQuickDelegatesQml.so -> x86_64-linux-gnu/libQt6WebEngineQuickDelegatesQml.so.6.7.2
libQt6WebEngineQuickDelegatesQml.so.6 -> x86_64-linux-gnu/libQt6WebEngineQuickDelegatesQml.so.6.7.2
libQt6WebEngineQuickDelegatesQml.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineQuickDelegatesQml.so.6.7.2
libQt6WebEngineQuick.so -> x86_64-linux-gnu/libQt6WebEngineQuick.so.6.7.2
libQt6WebEngineQuick.so.6 -> x86_64-linux-gnu/libQt6WebEngineQuick.so.6.7.2
libQt6WebEngineQuick.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineQuick.so.6.7.2
libQt6WebEngineWidgets.so -> x86_64-linux-gnu/libQt6WebEngineWidgets.so.6.7.2
libQt6WebEngineWidgets.so.6 -> x86_64-linux-gnu/libQt6WebEngineWidgets.so.6.7.2
libQt6WebEngineWidgets.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineWidgets.so.6.7.2
libQt6WebViewQuick.so -> x86_64-linux-gnu/libQt6WebViewQuick.so.6.7.2
libQt6WebViewQuick.so.6 -> x86_64-linux-gnu/libQt6WebViewQuick.so.6.7.2
libQt6WebViewQuick.so.6.7.2 -> x86_64-linux-gnu/libQt6WebViewQuick.so.6.7.2
libQt6WebView.so -> x86_64-linux-gnu/libQt6WebView.so.6.7.2
libQt6WebView.so.6 -> x86_64-linux-gnu/libQt6WebView.so.6.7.2
libQt6WebView.so.6.7.2 -> x86_64-linux-gnu/libQt6WebView.so.6.7.2
```

@CarlSchwan are you able to take a look at this please?

**Comment by CarlSchwan** [comment] 2024-10-01 09:17
> Can confirm here, but all the Qt libs in the flatpak are 6.7.2.
> 
> ```
> libQt6PdfQuick.so -> x86_64-linux-gnu/libQt6PdfQuick.so.6.7.2
> libQt6PdfQuick.so.6 -> x86_64-linux-gnu/libQt6PdfQuick.so.6.7.2
> libQt6PdfQuick.so.6.7.2 -> x86_64-linux-gnu/libQt6PdfQuick.so.6.7.2
> libQt6Pdf.so -> x86_64-linux-gnu/libQt6Pdf.so.6.7.2
> libQt6Pdf.so.6 -> x86_64-linux-gnu/libQt6Pdf.so.6.7.2
> libQt6Pdf.so.6.7.2 -> x86_64-linux-gnu/libQt6Pdf.so.6.7.2
> libQt6PdfWidgets.so -> x86_64-linux-gnu/libQt6PdfWidgets.so.6.7.2
> libQt6PdfWidgets.so.6 -> x86_64-linux-gnu/libQt6PdfWidgets.so.6.7.2
> libQt6PdfWidgets.so.6.7.2 -> x86_64-linux-gnu/libQt6PdfWidgets.so.6.7.2
> libQt6WebEngineCore.so -> x86_64-linux-gnu/libQt6WebEngineCore.so.6.7.2
> libQt6WebEngineCore.so.6 -> x86_64-linux-gnu/libQt6WebEngineCore.so.6.7.2
> libQt6WebEngineCore.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineCore.so.6.7.2
> libQt6WebEngineQuickDelegatesQml.so -> x86_64-linux-gnu/libQt6WebEngineQuickDelegatesQml.so.6.7.2
> libQt6WebEngineQuickDelegatesQml.so.6 -> x86_64-linux-gnu/libQt6WebEngineQuickDelegatesQml.so.6.7.2
> libQt6WebEngineQuickDelegatesQml.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineQuickDelegatesQml.so.6.7.2
> libQt6WebEngineQuick.so -> x86_64-linux-gnu/libQt6WebEngineQuick.so.6.7.2
> libQt6WebEngineQuick.so.6 -> x86_64-linux-gnu/libQt6WebEngineQuick.so.6.7.2
> libQt6WebEngineQuick.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineQuick.so.6.7.2
> libQt6WebEngineWidgets.so -> x86_64-linux-gnu/libQt6WebEngineWidgets.so.6.7.2
> libQt6WebEngineWidgets.so.6 -> x86_64-linux-gnu/libQt6WebEngineWidgets.so.6.7.2
> libQt6WebEngineWidgets.so.6.7.2 -> x86_64-linux-gnu/libQt6WebEngineWidgets.so.6.7.2
> libQt6WebViewQuick.so -> x86_64-linux-gnu/libQt6WebViewQuick.so.6.7.2
> libQt6WebViewQuick.so.6 -> x86_64-linux-gnu/libQt6WebViewQuick.so.6.7.2
> libQt6WebViewQuick.so.6.7.2 -> x86_64-linux-gnu/libQt6WebViewQuick.so.6.7.2
> libQt6WebView.so -> x86_64-linux-gnu/libQt6WebView.so.6.7.2
> libQt6WebView.so.6 -> x86_64-linux-gnu/libQt6WebView.so.6.7.2
> libQt6WebView.so.6.7.2 -> x86_64-linux-gnu/libQt6WebView.so.6.7.2
> ```
> 
> @CarlSchwan are you able to take a look at this please?

This is caused by QtWebengine not being in the KDE runtime. This happen after each update of the runtime. The work around is to rebuild the webengine base app, but the only way to solve this issue definitely is to move webengine to the kde runtime.

**Comment by travier** [comment] 2024-10-01 09:28
Hum, as far as I can see, https://github.com/flathub/io.qt.qtwebengine.BaseApp/commits/branch/6.7/ is still on 6.7.2

**Comment by travier** [comment] 2024-10-01 09:29
Ah, we've just merged the 6.7.3 update: https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/226, so we need to update qtwebengine as well.

**Comment by travier** [comment] 2024-10-01 09:33
https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/361

**Comment by Justinzobel** [comment] 2024-10-08 22:33
6.7.3 update done, this should now be resolved.

**Closed by Justinzobel** 2024-10-08 22:33 UTC
